CFLAGS = -Wall -I include

ifdef SYSROOT
CFLAGS += --sysroot=$(SYSROOT)
endif

all: i3ctransfer

i3ctransfer: i3ctransfer.c include/i3c/device.h include/i3c/i3cdev.h
	${CROSS_COMPILE}gcc $(CFLAGS) -o i3ctransfer i3ctransfer.c
